
crouch_disable: true

require_tool: true
tools:
  - WOODEN_AXE
  - STONE_AXE
  - COPPER_AXE
  - IRON_AXE
  - GOLDEN_AXE
  - DIAMOND_AXE
  - NETHERITE_AXE

tree:
  oak:
    logs:
      - OAK_LOG
    leaves:
      - OAK_LEAVES
      - flowering_azalea_leaves
      - azalea_leaves
    diagonal_cardinal: false
    true_diagonal: false
    large_log: false
    leaf_distance_x: 3
    leaf_distance_y: 2
    max_log_height: 6
    min_logs: 4
    min_leaves: 12
    separate_leaves: false
  birch:
    logs:
      - BIRCH_LOG
    leaves:
      - BIRCH_LEAVES
    diagonal_cardinal: false
    true_diagonal: false
    large_log: false
    leaf_distance_x: 3
    leaf_distance_y: 2
    max_log_height: 6
    min_logs: 4
    min_leaves: 12
    separate_leaves: false
  spruce:
    logs:
      - SPRUCE_LOG
    leaves:
      - SPRUCE_LEAVES
    diagonal_cardinal: false
    true_diagonal: false
    large_log: false
    leaf_distance_x: 3
    leaf_distance_y: 2
    max_log_height: 8
    min_logs: 4
    min_leaves: 12
    separate_leaves: true
  acacia:
    logs:
      - ACACIA_LOG
    leaves:
      - ACACIA_LEAVES
    diagonal_cardinal: true
    true_diagonal: false
    large_log: false
    leaf_distance_x: 3
    leaf_distance_y: 2
    max_log_height: 6
    min_logs: 4
    min_leaves: 12
    separate_leaves: false
  jungle:
    logs:
      - JUNGLE_LOG
    leaves:
      - JUNGLE_LEAVES
    diagonal_cardinal: false
    true_diagonal: false
    large_log: false
    leaf_distance_x: 3
    leaf_distance_y: 2
    max_log_height: 10
    min_logs: 4
    min_leaves: 12
    separate_leaves: false
  dark_oak:
    logs:
      - DARK_OAK_LOG
    leaves:
      - DARK_OAK_LEAVES
    diagonal_cardinal: false
    true_diagonal: true
    large_log: true
    leaf_distance_x: 5
    leaf_distance_y: 2
    max_log_height: 6
    min_logs: 4
    min_leaves: 12
    separate_leaves: false