
crouch_disable: true

tree_falling_damage: true

damage_tool_by_log_count: false
require_tool: true
tools:
  - WOODEN_AXE
  - STONE_AXE
  - COPPER_AXE
  - IRON_AXE
  - GOLDEN_AXE
  - DIAMOND_AXE
  - NETHERITE_AXE

replant_sapling: true
replantable_blocks:
  - dirt
  - grass_block
  - podzol
  - mycelium
  - coarse_dirt
  - rooted_dirt
  - moss_block
  - pale_moss_block
  - netherrack
  - warped_nylium
  - crimson_nylium
  - mud

tree:
  oak:
    logs:
      - OAK_LOG
      - STRIPPED_OAK_LOG
    leaves:
      - OAK_LEAVES
    sapling: OAK_SAPLING
    log_distance_x: 0
    log_distance_y: 6
    large_log: false
    leaf_distance_x: 2
    leaf_distance_y: 4
    min_logs: 4
    min_leaves: 12
    separate_leaves: false
    diagonal_leaves: false
  fancy_oak:
    logs:
      - OAK_LOG
      - STRIPPED_OAK_LOG
    leaves:
      - OAK_LEAVES
    sapling: OAK_SAPLING
    log_distance_x: 4
    log_distance_y: 12
    large_log: false
    leaf_distance_x: 4
    leaf_distance_y: 6
    min_logs: 9
    min_leaves: 24
    separate_leaves: false
    diagonal_leaves: false
  azalea:
    logs:
      - OAK_LOG
      - STRIPPED_OAK_LOG
    leaves:
      - flowering_azalea_leaves
      - azalea_leaves
    sapling: azalea
    log_distance_x: 4
    log_distance_y: 6
    large_log: false
    leaf_distance_x: 3
    leaf_distance_y: 4
    min_logs: 4
    min_leaves: 12
    separate_leaves: false
    diagonal_leaves: false
  birch:
    logs:
      - BIRCH_LOG
      - STRIPPED_BIRCH_LOG
    leaves:
      - BIRCH_LEAVES
    sapling: BIRCH_SAPLING
    log_distance_x: 0
    log_distance_y: 9
    large_log: false
    leaf_distance_x: 2
    leaf_distance_y: 3
    min_logs: 4
    min_leaves: 12
    separate_leaves: false
    diagonal_leaves: false
  spruce:
    logs:
      - SPRUCE_LOG
      - STRIPPED_SPRUCE_LOG
    leaves:
      - SPRUCE_LEAVES
    sapling: SPRUCE_SAPLING
    log_distance_x: 0
    log_distance_y: 8
    large_log: false
    leaf_distance_x: 3
    leaf_distance_y: 2
    min_logs: 4
    min_leaves: 12
    separate_leaves: true
    diagonal_leaves: false
  acacia:
    logs:
      - ACACIA_LOG
      - STRIPPED_ACACIA_LOG
    leaves:
      - ACACIA_LEAVES
    sapling: ACACIA_SAPLING
    log_distance_x: 4
    log_distance_y: 9
    large_log: false
    leaf_distance_x: 4
    leaf_distance_y: 2
    min_logs: 4
    min_leaves: 12
    separate_leaves: false
    diagonal_leaves: false
  jungle:
    logs:
      - JUNGLE_LOG
      - STRIPPED_JUNGLE_LOG
    leaves:
      - JUNGLE_LEAVES
    sapling: JUNGLE_SAPLING
    log_distance_x: 0
    log_distance_y: 11
    large_log: false
    leaf_distance_x: 2
    leaf_distance_y: 3
    min_logs: 4
    min_leaves: 12
    separate_leaves: false
    diagonal_leaves: false
  dark_oak:
    logs:
      - DARK_OAK_LOG
      - STRIPPED_DARK_OAK_LOG
    leaves:
      - DARK_OAK_LEAVES
    sapling: DARK_OAK_SAPLING
    log_distance_x: 2
    log_distance_y: 10
    large_log: true
    leaf_distance_x: 6
    leaf_distance_y: 2
    min_logs: 24
    min_leaves: 12
    separate_leaves: false
    diagonal_leaves: false
  cherry:
    logs:
      - CHERRY_LOG
      - STRIPPED_CHERRY_LOG
    leaves:
      - CHERRY_LEAVES
    sapling: CHERRY_SAPLING
    log_distance_x: 4
    log_distance_y: 10
    large_log: false
    leaf_distance_x: 7
    leaf_distance_y: 6
    min_logs: 4
    min_leaves: 12
    separate_leaves: false
    diagonal_leaves: false
  pale_oak:
    logs:
      - PALE_OAK_LOG
      - STRIPPED_PALE_OAK_LOG
    leaves:
      - PALE_OAK_LEAVES
    sapling: PALE_OAK_SAPLING
    log_distance_x: 3
    log_distance_y: 10
    large_log: true
    leaf_distance_x: 5
    leaf_distance_y: 2
    min_logs: 24
    min_leaves: 12
    separate_leaves: false
    diagonal_leaves: false
  large_spruce:
    logs:
      - SPRUCE_LOG
      - STRIPPED_SPRUCE_LOG
    leaves:
      - SPRUCE_LEAVES
    sapling: SPRUCE_SAPLING
    log_distance_x: 1
    log_distance_y: 30
    large_log: true
    leaf_distance_x: 6
    leaf_distance_y: 3
    min_logs: 40
    min_leaves: 9
    separate_leaves: false
    diagonal_leaves: true
  large_jungle:
    logs:
      - JUNGLE_LOG
      - STRIPPED_JUNGLE_LOG
    leaves:
      - JUNGLE_LEAVES
    sapling: JUNGLE_SAPLING
    log_distance_x: 5
    log_distance_y: 30
    large_log: true
    leaf_distance_x: 9
    leaf_distance_y: 3
    min_logs: 40
    min_leaves: 9
    separate_leaves: false
    diagonal_leaves: true
  red_mushroom:
    logs:
      - MUSHROOM_STEM
    leaves:
      - RED_MUSHROOM_BLOCK
    sapling: red_mushroom
    log_distance_x: 0
    log_distance_y: 10
    large_log: false
    leaf_distance_x: 2
    leaf_distance_y: 5
    min_logs: 4
    min_leaves: 12
    separate_leaves: false
    diagonal_leaves: true
  brown_mushroom:
    logs:
      - MUSHROOM_STEM
    leaves:
      - BROWN_MUSHROOM_BLOCK
    sapling: brown_mushroom
    log_distance_x: 0
    log_distance_y: 10
    large_log: false
    leaf_distance_x: 3
    leaf_distance_y: 0
    min_logs: 4
    min_leaves: 12
    separate_leaves: false
    diagonal_leaves: false
  warped_fungus:
    logs:
      - warped_stem
    leaves:
      - warped_wart_block
      - shroomlight
    sapling: warped_fungus
    log_distance_x: 0
    log_distance_y: 12
    large_log: false
    leaf_distance_x: 3
    leaf_distance_y: 8
    min_logs: 4
    min_leaves: 12
    separate_leaves: false
    diagonal_leaves: true
  crimson_fungus:
    logs:
      - crimson_stem
    leaves:
      - nether_wart_block
      - shroomlight
    sapling: crimson_fungus
    log_distance_x: 0
    log_distance_y: 12
    large_log: false
    leaf_distance_x: 3
    leaf_distance_y: 8
    min_logs: 4
    min_leaves: 12
    separate_leaves: false
    diagonal_leaves: true
  large_crimson_fungus:
    logs:
      - crimson_stem
    leaves:
      - nether_wart_block
      - shroomlight
    sapling: crimson_fungus
    log_distance_x: 2
    log_distance_y: 12
    large_log: false
    leaf_distance_x: 4
    leaf_distance_y: 8
    min_logs: 24
    min_leaves: 12
    separate_leaves: false
    diagonal_leaves: true
  mangrove:
    logs:
      - mangrove_roots
      - muddy_mangrove_roots
      - mangrove_log
      - stripped_mangrove_log
    leaves:
      - mangrove_leaves
    sapling: mangrove_propagule
    log_distance_x: 8
    log_distance_y: 21
    downward_logs: true
    large_log: false
    leaf_distance_x: 8
    leaf_distance_y: 25
    min_logs: 12
    min_leaves: 24
    separate_leaves: false
    diagonal_leaves: false
